spring:
  profiles.active: dev
  sql.init.mode: always
  mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER

---

spring:
  config.activate.on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
security.jwt.token:
  secret-key: ${secret-key}
  expire-length: ${jwt-validity}

---

spring:
  config.activate.on-profile: dev
  datasource:
    url: jdbc:h2:~/test;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
security.jwt.token:
  secret-key:
    eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno
  expire-length: 3600000
